- hosts: localhost
  tasks:
  # Downlaod the script to create instance
  - name: download create-instance.sh
    get_url:
       url: https://raw.githubusercontent.com/praveensiddu/aws/main/k3s-aws/create-instance.sh
       dest: .
       force: yes

  # Run create instance. The newly created instance is configure with ssh public key bastion-to-other-hosts-key
  - name: run create-instance.sh
    shell: bash create-instance.sh
    environment:
        MYSSHKEYNAME: 'bastion-to-other-hosts-key'
        INSTNAME: "{{INSTNAME}}"
        
  - name: download get-private-ip.sh
    get_url:
       url: https://raw.githubusercontent.com/praveensiddu/aws/main/utils/get-private-ip.sh
       dest: .
       force: yes

  - name: Waiting the instance to get to running state
    pause: seconds=60

  - name: Get private IP of the new instance
    shell: bash get-private-ip.sh {{INSTNAME}}
    register: command_output
        
  - debug: msg="{{command_output.stdout}}"

  - set_fact:
      ip_from_ec2: "{{ command_output.stdout }}"
    
  - name: add host to group 'just_created' with variable foo=42
    add_host:
      name: "{{ ip_from_ec2 }}"
      groups: just_created
    
  - name: download add-ingress-to-secgrp.sh
    get_url:
       url: https://raw.githubusercontent.com/praveensiddu/aws/main/utils/add-ingress-to-secgrp.sh
       dest: .
       force: yes

  - name: SSH access to bastion
    shell: bash add-ingress-to-secgrp.sh {{INSTNAME}}-secgrp outgoing-from-bastion-secgrp 22
    ignore_errors: yes

  - name: port 80 access to loadbalancer
    shell: bash add-ingress-to-secgrp.sh {{INSTNAME}}-secgrp outgoing-from-loadbalancer-secgrp 80
    ignore_errors: yes
    
  - name: port 443 access to loadbalancer
    shell: bash add-ingress-to-secgrp.sh {{INSTNAME}}-secgrp outgoing-from-loadbalancer-secgrp 443
    ignore_errors: yes

- hosts: just_created
  become: true
  tasks:
  
  - name: download cloud-init
    get_url:
       url: https://raw.githubusercontent.com/praveensiddu/aws/main/k3s-aws/cloud-init.sh
       dest: .
       force: yes

  - name: run cloud-init
    shell: bash cloud-init.sh

 
  - name: run K3S
    shell: bash curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
    
   
  - name: deploy nginx
    shell: kubectl apply -f https://raw.githubusercontent.com/praveensiddu/aws/main/k3s-aws/manifests/nginx_deployment.yaml
 
   
  - name: deploy nginx
    shell: kubectl apply -f https://raw.githubusercontent.com/praveensiddu/aws/main/k3s-aws/manifests/nginx_service.yaml
    
   
  - name: deploy nginx
    shell: kubectl apply -f https://raw.githubusercontent.com/praveensiddu/aws/main/k3s-aws/manifests/nginx_ingress.yaml
    

